// Code generated by go-swagger; DO NOT EDIT.

package user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// EditFieldUsingPUT1OKCode is the HTTP code returned for type EditFieldUsingPUT1OK
const EditFieldUsingPUT1OKCode int = 200

/*EditFieldUsingPUT1OK OK

swagger:response editFieldUsingPUT1OK
*/
type EditFieldUsingPUT1OK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewEditFieldUsingPUT1OK creates EditFieldUsingPUT1OK with default headers values
func NewEditFieldUsingPUT1OK() *EditFieldUsingPUT1OK {
	return &EditFieldUsingPUT1OK{}
}

// WithPayload adds the payload to the edit field using p u t1 o k response
func (o *EditFieldUsingPUT1OK) WithPayload(payload *models.User) *EditFieldUsingPUT1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit field using p u t1 o k response
func (o *EditFieldUsingPUT1OK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditFieldUsingPUT1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EditFieldUsingPUT1CreatedCode is the HTTP code returned for type EditFieldUsingPUT1Created
const EditFieldUsingPUT1CreatedCode int = 201

/*EditFieldUsingPUT1Created Created

swagger:response editFieldUsingPUT1Created
*/
type EditFieldUsingPUT1Created struct {
}

// NewEditFieldUsingPUT1Created creates EditFieldUsingPUT1Created with default headers values
func NewEditFieldUsingPUT1Created() *EditFieldUsingPUT1Created {
	return &EditFieldUsingPUT1Created{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUT1Created) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EditFieldUsingPUT1UnauthorizedCode is the HTTP code returned for type EditFieldUsingPUT1Unauthorized
const EditFieldUsingPUT1UnauthorizedCode int = 401

/*EditFieldUsingPUT1Unauthorized Unauthorized

swagger:response editFieldUsingPUT1Unauthorized
*/
type EditFieldUsingPUT1Unauthorized struct {
}

// NewEditFieldUsingPUT1Unauthorized creates EditFieldUsingPUT1Unauthorized with default headers values
func NewEditFieldUsingPUT1Unauthorized() *EditFieldUsingPUT1Unauthorized {
	return &EditFieldUsingPUT1Unauthorized{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUT1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// EditFieldUsingPUT1ForbiddenCode is the HTTP code returned for type EditFieldUsingPUT1Forbidden
const EditFieldUsingPUT1ForbiddenCode int = 403

/*EditFieldUsingPUT1Forbidden Forbidden

swagger:response editFieldUsingPUT1Forbidden
*/
type EditFieldUsingPUT1Forbidden struct {
}

// NewEditFieldUsingPUT1Forbidden creates EditFieldUsingPUT1Forbidden with default headers values
func NewEditFieldUsingPUT1Forbidden() *EditFieldUsingPUT1Forbidden {
	return &EditFieldUsingPUT1Forbidden{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUT1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// EditFieldUsingPUT1NotFoundCode is the HTTP code returned for type EditFieldUsingPUT1NotFound
const EditFieldUsingPUT1NotFoundCode int = 404

/*EditFieldUsingPUT1NotFound Not Found

swagger:response editFieldUsingPUT1NotFound
*/
type EditFieldUsingPUT1NotFound struct {
}

// NewEditFieldUsingPUT1NotFound creates EditFieldUsingPUT1NotFound with default headers values
func NewEditFieldUsingPUT1NotFound() *EditFieldUsingPUT1NotFound {
	return &EditFieldUsingPUT1NotFound{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUT1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
