package user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/roscopecoltran/admin-on-rest-server/server/api"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// BusinessLogicEditFieldUsingPUT1 executes the core logic of the related
// route endpoint.
func BusinessLogicEditFieldUsingPUT1(f func(ctx *gin.Context, params *EditFieldUsingPUT1Params) *api.Response) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		// generate params from request
		params := &EditFieldUsingPUT1Params{}
		err := params.bindRequest(ctx)
		if err != nil {
			errObj := err.(*errors.CompositeError)
			problem := api.Problem{
				Title:  "Unprocessable Entity.",
				Status: int(errObj.Code()),
				Detail: errObj.Error(),
			}
			ctx.Writer.Header().Set("Content-Type", "application/problem+json")
			ctx.JSON(problem.Status, problem)
			return
		}

		resp := f(ctx, params)
		switch resp.Code {
		case http.StatusNoContent:
			ctx.AbortWithStatus(resp.Code)
		default:
			ctx.JSON(resp.Code, resp.Body)
		}
	}
}

// EditFieldUsingPUT1Params contains all the bound params for the edit field using p u t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters editFieldUsingPUT_1
type EditFieldUsingPUT1Params struct {

	/*id
	  Required: true
	  In: path
	*/
	ID string
	/*user
	  Required: true
	  In: body
	*/
	User *models.User
}

// EditFieldUsingPUT1ParamsFromCtx gets the params struct from the gin context.
func EditFieldUsingPUT1ParamsFromCtx(ctx *gin.Context) *EditFieldUsingPUT1Params {
	params, _ := ctx.Get("params")
	return params.(*EditFieldUsingPUT1Params)
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *EditFieldUsingPUT1Params) bindRequest(ctx *gin.Context) error {
	var res []error
	formats := strfmt.NewFormats()

	rID := []string{ctx.Param("id")}
	if err := o.bindID(rID, true, formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(ctx.Request) {
		var body models.User
		if err := ctx.BindJSON(&body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("user", "body"))
			} else {
				res = append(res, errors.NewParseError("user", "body", "", err))
			}

		} else {
			if err := body.Validate(formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.User = &body
			}
		}

	} else {
		res = append(res, errors.Required("user", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditFieldUsingPUT1Params) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}

// vim: ft=go
