// Code generated by go-swagger; DO NOT EDIT.

package user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// FindUserUsingGET1OKCode is the HTTP code returned for type FindUserUsingGET1OK
const FindUserUsingGET1OKCode int = 200

/*FindUserUsingGET1OK OK

swagger:response findUserUsingGET1OK
*/
type FindUserUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewFindUserUsingGET1OK creates FindUserUsingGET1OK with default headers values
func NewFindUserUsingGET1OK() *FindUserUsingGET1OK {
	return &FindUserUsingGET1OK{}
}

// WithPayload adds the payload to the find user using g e t1 o k response
func (o *FindUserUsingGET1OK) WithPayload(payload *models.User) *FindUserUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find user using g e t1 o k response
func (o *FindUserUsingGET1OK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindUserUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindUserUsingGET1UnauthorizedCode is the HTTP code returned for type FindUserUsingGET1Unauthorized
const FindUserUsingGET1UnauthorizedCode int = 401

/*FindUserUsingGET1Unauthorized Unauthorized

swagger:response findUserUsingGET1Unauthorized
*/
type FindUserUsingGET1Unauthorized struct {
}

// NewFindUserUsingGET1Unauthorized creates FindUserUsingGET1Unauthorized with default headers values
func NewFindUserUsingGET1Unauthorized() *FindUserUsingGET1Unauthorized {
	return &FindUserUsingGET1Unauthorized{}
}

// WriteResponse to the client
func (o *FindUserUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindUserUsingGET1ForbiddenCode is the HTTP code returned for type FindUserUsingGET1Forbidden
const FindUserUsingGET1ForbiddenCode int = 403

/*FindUserUsingGET1Forbidden Forbidden

swagger:response findUserUsingGET1Forbidden
*/
type FindUserUsingGET1Forbidden struct {
}

// NewFindUserUsingGET1Forbidden creates FindUserUsingGET1Forbidden with default headers values
func NewFindUserUsingGET1Forbidden() *FindUserUsingGET1Forbidden {
	return &FindUserUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *FindUserUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindUserUsingGET1NotFoundCode is the HTTP code returned for type FindUserUsingGET1NotFound
const FindUserUsingGET1NotFoundCode int = 404

/*FindUserUsingGET1NotFound Not Found

swagger:response findUserUsingGET1NotFound
*/
type FindUserUsingGET1NotFound struct {
}

// NewFindUserUsingGET1NotFound creates FindUserUsingGET1NotFound with default headers values
func NewFindUserUsingGET1NotFound() *FindUserUsingGET1NotFound {
	return &FindUserUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *FindUserUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
