// Code generated by go-swagger; DO NOT EDIT.

package user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindUserUsingGET1HandlerFunc turns a function with the right signature into a find user using g e t 1 handler
type FindUserUsingGET1HandlerFunc func(FindUserUsingGET1Params) middleware.Responder

// Handle executing the request and returning a response
func (fn FindUserUsingGET1HandlerFunc) Handle(params FindUserUsingGET1Params) middleware.Responder {
	return fn(params)
}

// FindUserUsingGET1Handler interface for that can handle valid find user using g e t 1 params
type FindUserUsingGET1Handler interface {
	Handle(FindUserUsingGET1Params) middleware.Responder
}

// NewFindUserUsingGET1 creates a new http.Handler for the find user using g e t 1 operation
func NewFindUserUsingGET1(ctx *middleware.Context, handler FindUserUsingGET1Handler) *FindUserUsingGET1 {
	return &FindUserUsingGET1{Context: ctx, Handler: handler}
}

/*FindUserUsingGET1 swagger:route GET /user/_users/{userId} user-controller findUserUsingGET1

findUser

*/
type FindUserUsingGET1 struct {
	Context *middleware.Context
	Handler FindUserUsingGET1Handler
}

func (o *FindUserUsingGET1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindUserUsingGET1Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
