// Code generated by go-swagger; DO NOT EDIT.

package user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAuthenticatedUserUsingGETHandlerFunc turns a function with the right signature into a get authenticated user using g e t handler
type GetAuthenticatedUserUsingGETHandlerFunc func(GetAuthenticatedUserUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthenticatedUserUsingGETHandlerFunc) Handle(params GetAuthenticatedUserUsingGETParams) middleware.Responder {
	return fn(params)
}

// GetAuthenticatedUserUsingGETHandler interface for that can handle valid get authenticated user using g e t params
type GetAuthenticatedUserUsingGETHandler interface {
	Handle(GetAuthenticatedUserUsingGETParams) middleware.Responder
}

// NewGetAuthenticatedUserUsingGET creates a new http.Handler for the get authenticated user using g e t operation
func NewGetAuthenticatedUserUsingGET(ctx *middleware.Context, handler GetAuthenticatedUserUsingGETHandler) *GetAuthenticatedUserUsingGET {
	return &GetAuthenticatedUserUsingGET{Context: ctx, Handler: handler}
}

/*GetAuthenticatedUserUsingGET swagger:route GET /user/me user-controller getAuthenticatedUserUsingGET

getAuthenticatedUser

*/
type GetAuthenticatedUserUsingGET struct {
	Context *middleware.Context
	Handler GetAuthenticatedUserUsingGETHandler
}

func (o *GetAuthenticatedUserUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAuthenticatedUserUsingGETParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
