// Code generated by go-swagger; DO NOT EDIT.

package user_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListUsingGET3Params creates a new ListUsingGET3Params object
// with the default values initialized.
func NewListUsingGET3Params() ListUsingGET3Params {
	var ()
	return ListUsingGET3Params{}
}

// ListUsingGET3Params contains all the bound params for the list using g e t 3 operation
// typically these are obtained from a http.Request
//
// swagger:parameters listUsingGET_3
type ListUsingGET3Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ListUsingGET3Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
