// Code generated by go-swagger; DO NOT EDIT.

package role_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// AddRoleUsingPOSTOKCode is the HTTP code returned for type AddRoleUsingPOSTOK
const AddRoleUsingPOSTOKCode int = 200

/*AddRoleUsingPOSTOK OK

swagger:response addRoleUsingPOSTOK
*/
type AddRoleUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Role `json:"body,omitempty"`
}

// NewAddRoleUsingPOSTOK creates AddRoleUsingPOSTOK with default headers values
func NewAddRoleUsingPOSTOK() *AddRoleUsingPOSTOK {
	return &AddRoleUsingPOSTOK{}
}

// WithPayload adds the payload to the add role using p o s t o k response
func (o *AddRoleUsingPOSTOK) WithPayload(payload *models.Role) *AddRoleUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add role using p o s t o k response
func (o *AddRoleUsingPOSTOK) SetPayload(payload *models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRoleUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddRoleUsingPOSTCreatedCode is the HTTP code returned for type AddRoleUsingPOSTCreated
const AddRoleUsingPOSTCreatedCode int = 201

/*AddRoleUsingPOSTCreated Created

swagger:response addRoleUsingPOSTCreated
*/
type AddRoleUsingPOSTCreated struct {
}

// NewAddRoleUsingPOSTCreated creates AddRoleUsingPOSTCreated with default headers values
func NewAddRoleUsingPOSTCreated() *AddRoleUsingPOSTCreated {
	return &AddRoleUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *AddRoleUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddRoleUsingPOSTUnauthorizedCode is the HTTP code returned for type AddRoleUsingPOSTUnauthorized
const AddRoleUsingPOSTUnauthorizedCode int = 401

/*AddRoleUsingPOSTUnauthorized Unauthorized

swagger:response addRoleUsingPOSTUnauthorized
*/
type AddRoleUsingPOSTUnauthorized struct {
}

// NewAddRoleUsingPOSTUnauthorized creates AddRoleUsingPOSTUnauthorized with default headers values
func NewAddRoleUsingPOSTUnauthorized() *AddRoleUsingPOSTUnauthorized {
	return &AddRoleUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *AddRoleUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddRoleUsingPOSTForbiddenCode is the HTTP code returned for type AddRoleUsingPOSTForbidden
const AddRoleUsingPOSTForbiddenCode int = 403

/*AddRoleUsingPOSTForbidden Forbidden

swagger:response addRoleUsingPOSTForbidden
*/
type AddRoleUsingPOSTForbidden struct {
}

// NewAddRoleUsingPOSTForbidden creates AddRoleUsingPOSTForbidden with default headers values
func NewAddRoleUsingPOSTForbidden() *AddRoleUsingPOSTForbidden {
	return &AddRoleUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *AddRoleUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddRoleUsingPOSTNotFoundCode is the HTTP code returned for type AddRoleUsingPOSTNotFound
const AddRoleUsingPOSTNotFoundCode int = 404

/*AddRoleUsingPOSTNotFound Not Found

swagger:response addRoleUsingPOSTNotFound
*/
type AddRoleUsingPOSTNotFound struct {
}

// NewAddRoleUsingPOSTNotFound creates AddRoleUsingPOSTNotFound with default headers values
func NewAddRoleUsingPOSTNotFound() *AddRoleUsingPOSTNotFound {
	return &AddRoleUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *AddRoleUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
