// Code generated by go-swagger; DO NOT EDIT.

package role_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// EditRoleUsingPUTOKCode is the HTTP code returned for type EditRoleUsingPUTOK
const EditRoleUsingPUTOKCode int = 200

/*EditRoleUsingPUTOK OK

swagger:response editRoleUsingPUTOK
*/
type EditRoleUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Role `json:"body,omitempty"`
}

// NewEditRoleUsingPUTOK creates EditRoleUsingPUTOK with default headers values
func NewEditRoleUsingPUTOK() *EditRoleUsingPUTOK {
	return &EditRoleUsingPUTOK{}
}

// WithPayload adds the payload to the edit role using p u t o k response
func (o *EditRoleUsingPUTOK) WithPayload(payload *models.Role) *EditRoleUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit role using p u t o k response
func (o *EditRoleUsingPUTOK) SetPayload(payload *models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditRoleUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EditRoleUsingPUTCreatedCode is the HTTP code returned for type EditRoleUsingPUTCreated
const EditRoleUsingPUTCreatedCode int = 201

/*EditRoleUsingPUTCreated Created

swagger:response editRoleUsingPUTCreated
*/
type EditRoleUsingPUTCreated struct {
}

// NewEditRoleUsingPUTCreated creates EditRoleUsingPUTCreated with default headers values
func NewEditRoleUsingPUTCreated() *EditRoleUsingPUTCreated {
	return &EditRoleUsingPUTCreated{}
}

// WriteResponse to the client
func (o *EditRoleUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EditRoleUsingPUTUnauthorizedCode is the HTTP code returned for type EditRoleUsingPUTUnauthorized
const EditRoleUsingPUTUnauthorizedCode int = 401

/*EditRoleUsingPUTUnauthorized Unauthorized

swagger:response editRoleUsingPUTUnauthorized
*/
type EditRoleUsingPUTUnauthorized struct {
}

// NewEditRoleUsingPUTUnauthorized creates EditRoleUsingPUTUnauthorized with default headers values
func NewEditRoleUsingPUTUnauthorized() *EditRoleUsingPUTUnauthorized {
	return &EditRoleUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *EditRoleUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// EditRoleUsingPUTForbiddenCode is the HTTP code returned for type EditRoleUsingPUTForbidden
const EditRoleUsingPUTForbiddenCode int = 403

/*EditRoleUsingPUTForbidden Forbidden

swagger:response editRoleUsingPUTForbidden
*/
type EditRoleUsingPUTForbidden struct {
}

// NewEditRoleUsingPUTForbidden creates EditRoleUsingPUTForbidden with default headers values
func NewEditRoleUsingPUTForbidden() *EditRoleUsingPUTForbidden {
	return &EditRoleUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *EditRoleUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// EditRoleUsingPUTNotFoundCode is the HTTP code returned for type EditRoleUsingPUTNotFound
const EditRoleUsingPUTNotFoundCode int = 404

/*EditRoleUsingPUTNotFound Not Found

swagger:response editRoleUsingPUTNotFound
*/
type EditRoleUsingPUTNotFound struct {
}

// NewEditRoleUsingPUTNotFound creates EditRoleUsingPUTNotFound with default headers values
func NewEditRoleUsingPUTNotFound() *EditRoleUsingPUTNotFound {
	return &EditRoleUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *EditRoleUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
