// Code generated by go-swagger; DO NOT EDIT.

package role_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// FindRoleUsingGET1OKCode is the HTTP code returned for type FindRoleUsingGET1OK
const FindRoleUsingGET1OKCode int = 200

/*FindRoleUsingGET1OK OK

swagger:response findRoleUsingGET1OK
*/
type FindRoleUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.Role `json:"body,omitempty"`
}

// NewFindRoleUsingGET1OK creates FindRoleUsingGET1OK with default headers values
func NewFindRoleUsingGET1OK() *FindRoleUsingGET1OK {
	return &FindRoleUsingGET1OK{}
}

// WithPayload adds the payload to the find role using g e t1 o k response
func (o *FindRoleUsingGET1OK) WithPayload(payload *models.Role) *FindRoleUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find role using g e t1 o k response
func (o *FindRoleUsingGET1OK) SetPayload(payload *models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindRoleUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindRoleUsingGET1UnauthorizedCode is the HTTP code returned for type FindRoleUsingGET1Unauthorized
const FindRoleUsingGET1UnauthorizedCode int = 401

/*FindRoleUsingGET1Unauthorized Unauthorized

swagger:response findRoleUsingGET1Unauthorized
*/
type FindRoleUsingGET1Unauthorized struct {
}

// NewFindRoleUsingGET1Unauthorized creates FindRoleUsingGET1Unauthorized with default headers values
func NewFindRoleUsingGET1Unauthorized() *FindRoleUsingGET1Unauthorized {
	return &FindRoleUsingGET1Unauthorized{}
}

// WriteResponse to the client
func (o *FindRoleUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindRoleUsingGET1ForbiddenCode is the HTTP code returned for type FindRoleUsingGET1Forbidden
const FindRoleUsingGET1ForbiddenCode int = 403

/*FindRoleUsingGET1Forbidden Forbidden

swagger:response findRoleUsingGET1Forbidden
*/
type FindRoleUsingGET1Forbidden struct {
}

// NewFindRoleUsingGET1Forbidden creates FindRoleUsingGET1Forbidden with default headers values
func NewFindRoleUsingGET1Forbidden() *FindRoleUsingGET1Forbidden {
	return &FindRoleUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *FindRoleUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindRoleUsingGET1NotFoundCode is the HTTP code returned for type FindRoleUsingGET1NotFound
const FindRoleUsingGET1NotFoundCode int = 404

/*FindRoleUsingGET1NotFound Not Found

swagger:response findRoleUsingGET1NotFound
*/
type FindRoleUsingGET1NotFound struct {
}

// NewFindRoleUsingGET1NotFound creates FindRoleUsingGET1NotFound with default headers values
func NewFindRoleUsingGET1NotFound() *FindRoleUsingGET1NotFound {
	return &FindRoleUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *FindRoleUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
