package role_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/go-openapi/errors"
	"github.com/mikkeloscar/gin-swagger/api"

	strfmt "github.com/go-openapi/strfmt"
)

// BusinessLogicFindRoleUsingGET1 executes the core logic of the related
// route endpoint.
func BusinessLogicFindRoleUsingGET1(f func(ctx *gin.Context, params *FindRoleUsingGET1Params) *api.Response) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		// generate params from request
		params := &FindRoleUsingGET1Params{}
		err := params.bindRequest(ctx)
		if err != nil {
			errObj := err.(*errors.CompositeError)
			problem := api.Problem{
				Title:  "Unprocessable Entity.",
				Status: int(errObj.Code()),
				Detail: errObj.Error(),
			}
			ctx.Writer.Header().Set("Content-Type", "application/problem+json")
			ctx.JSON(problem.Status, problem)
			return
		}

		resp := f(ctx, params)
		switch resp.Code {
		case http.StatusNoContent:
			ctx.AbortWithStatus(resp.Code)
		default:
			ctx.JSON(resp.Code, resp.Body)
		}
	}
}

// FindRoleUsingGET1Params contains all the bound params for the find role using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters findRoleUsingGET_1
type FindRoleUsingGET1Params struct {

	/*roleId
	  Required: true
	  In: path
	*/
	RoleID string
}

// FindRoleUsingGET1ParamsFromCtx gets the params struct from the gin context.
func FindRoleUsingGET1ParamsFromCtx(ctx *gin.Context) *FindRoleUsingGET1Params {
	params, _ := ctx.Get("params")
	return params.(*FindRoleUsingGET1Params)
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindRoleUsingGET1Params) bindRequest(ctx *gin.Context) error {
	var res []error
	formats := strfmt.NewFormats()

	rRoleID := []string{ctx.Param("roleId")}
	if err := o.bindRoleID(rRoleID, true, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindRoleUsingGET1Params) bindRoleID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.RoleID = raw

	return nil
}

// vim: ft=go
