// Code generated by go-swagger; DO NOT EDIT.

package role_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// ListUsingGET2OKCode is the HTTP code returned for type ListUsingGET2OK
const ListUsingGET2OKCode int = 200

/*ListUsingGET2OK OK

swagger:response listUsingGET2OK
*/
type ListUsingGET2OK struct {

	/*
	  In: Body
	*/
	Payload []*models.Role `json:"body,omitempty"`
}

// NewListUsingGET2OK creates ListUsingGET2OK with default headers values
func NewListUsingGET2OK() *ListUsingGET2OK {
	return &ListUsingGET2OK{}
}

// WithPayload adds the payload to the list using g e t2 o k response
func (o *ListUsingGET2OK) WithPayload(payload []*models.Role) *ListUsingGET2OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list using g e t2 o k response
func (o *ListUsingGET2OK) SetPayload(payload []*models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsingGET2OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Role, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// ListUsingGET2UnauthorizedCode is the HTTP code returned for type ListUsingGET2Unauthorized
const ListUsingGET2UnauthorizedCode int = 401

/*ListUsingGET2Unauthorized Unauthorized

swagger:response listUsingGET2Unauthorized
*/
type ListUsingGET2Unauthorized struct {
}

// NewListUsingGET2Unauthorized creates ListUsingGET2Unauthorized with default headers values
func NewListUsingGET2Unauthorized() *ListUsingGET2Unauthorized {
	return &ListUsingGET2Unauthorized{}
}

// WriteResponse to the client
func (o *ListUsingGET2Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ListUsingGET2ForbiddenCode is the HTTP code returned for type ListUsingGET2Forbidden
const ListUsingGET2ForbiddenCode int = 403

/*ListUsingGET2Forbidden Forbidden

swagger:response listUsingGET2Forbidden
*/
type ListUsingGET2Forbidden struct {
}

// NewListUsingGET2Forbidden creates ListUsingGET2Forbidden with default headers values
func NewListUsingGET2Forbidden() *ListUsingGET2Forbidden {
	return &ListUsingGET2Forbidden{}
}

// WriteResponse to the client
func (o *ListUsingGET2Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// ListUsingGET2NotFoundCode is the HTTP code returned for type ListUsingGET2NotFound
const ListUsingGET2NotFoundCode int = 404

/*ListUsingGET2NotFound Not Found

swagger:response listUsingGET2NotFound
*/
type ListUsingGET2NotFound struct {
}

// NewListUsingGET2NotFound creates ListUsingGET2NotFound with default headers values
func NewListUsingGET2NotFound() *ListUsingGET2NotFound {
	return &ListUsingGET2NotFound{}
}

// WriteResponse to the client
func (o *ListUsingGET2NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
