// Code generated by go-swagger; DO NOT EDIT.

package apply_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// NewApplyUsingPOSTParams creates a new ApplyUsingPOSTParams object
// with the default values initialized.
func NewApplyUsingPOSTParams() ApplyUsingPOSTParams {
	var ()
	return ApplyUsingPOSTParams{}
}

// ApplyUsingPOSTParams contains all the bound params for the apply using p o s t operation
// typically these are obtained from a http.Request
//
// swagger:parameters applyUsingPOST
type ApplyUsingPOSTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*apply
	  Required: true
	  In: body
	*/
	Apply *models.Apply
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ApplyUsingPOSTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Apply
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("apply", "body"))
			} else {
				res = append(res, errors.NewParseError("apply", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Apply = &body
			}
		}

	} else {
		res = append(res, errors.Required("apply", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
