// Code generated by go-swagger; DO NOT EDIT.

package authentication_rest_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RefreshAndGetAuthenticationTokenUsingGETOKCode is the HTTP code returned for type RefreshAndGetAuthenticationTokenUsingGETOK
const RefreshAndGetAuthenticationTokenUsingGETOKCode int = 200

/*RefreshAndGetAuthenticationTokenUsingGETOK OK

swagger:response refreshAndGetAuthenticationTokenUsingGETOK
*/
type RefreshAndGetAuthenticationTokenUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload RefreshAndGetAuthenticationTokenUsingGETOKBody `json:"body,omitempty"`
}

// NewRefreshAndGetAuthenticationTokenUsingGETOK creates RefreshAndGetAuthenticationTokenUsingGETOK with default headers values
func NewRefreshAndGetAuthenticationTokenUsingGETOK() *RefreshAndGetAuthenticationTokenUsingGETOK {
	return &RefreshAndGetAuthenticationTokenUsingGETOK{}
}

// WithPayload adds the payload to the refresh and get authentication token using g e t o k response
func (o *RefreshAndGetAuthenticationTokenUsingGETOK) WithPayload(payload RefreshAndGetAuthenticationTokenUsingGETOKBody) *RefreshAndGetAuthenticationTokenUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh and get authentication token using g e t o k response
func (o *RefreshAndGetAuthenticationTokenUsingGETOK) SetPayload(payload RefreshAndGetAuthenticationTokenUsingGETOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshAndGetAuthenticationTokenUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// RefreshAndGetAuthenticationTokenUsingGETUnauthorizedCode is the HTTP code returned for type RefreshAndGetAuthenticationTokenUsingGETUnauthorized
const RefreshAndGetAuthenticationTokenUsingGETUnauthorizedCode int = 401

/*RefreshAndGetAuthenticationTokenUsingGETUnauthorized Unauthorized

swagger:response refreshAndGetAuthenticationTokenUsingGETUnauthorized
*/
type RefreshAndGetAuthenticationTokenUsingGETUnauthorized struct {
}

// NewRefreshAndGetAuthenticationTokenUsingGETUnauthorized creates RefreshAndGetAuthenticationTokenUsingGETUnauthorized with default headers values
func NewRefreshAndGetAuthenticationTokenUsingGETUnauthorized() *RefreshAndGetAuthenticationTokenUsingGETUnauthorized {
	return &RefreshAndGetAuthenticationTokenUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *RefreshAndGetAuthenticationTokenUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RefreshAndGetAuthenticationTokenUsingGETForbiddenCode is the HTTP code returned for type RefreshAndGetAuthenticationTokenUsingGETForbidden
const RefreshAndGetAuthenticationTokenUsingGETForbiddenCode int = 403

/*RefreshAndGetAuthenticationTokenUsingGETForbidden Forbidden

swagger:response refreshAndGetAuthenticationTokenUsingGETForbidden
*/
type RefreshAndGetAuthenticationTokenUsingGETForbidden struct {
}

// NewRefreshAndGetAuthenticationTokenUsingGETForbidden creates RefreshAndGetAuthenticationTokenUsingGETForbidden with default headers values
func NewRefreshAndGetAuthenticationTokenUsingGETForbidden() *RefreshAndGetAuthenticationTokenUsingGETForbidden {
	return &RefreshAndGetAuthenticationTokenUsingGETForbidden{}
}

// WriteResponse to the client
func (o *RefreshAndGetAuthenticationTokenUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// RefreshAndGetAuthenticationTokenUsingGETNotFoundCode is the HTTP code returned for type RefreshAndGetAuthenticationTokenUsingGETNotFound
const RefreshAndGetAuthenticationTokenUsingGETNotFoundCode int = 404

/*RefreshAndGetAuthenticationTokenUsingGETNotFound Not Found

swagger:response refreshAndGetAuthenticationTokenUsingGETNotFound
*/
type RefreshAndGetAuthenticationTokenUsingGETNotFound struct {
}

// NewRefreshAndGetAuthenticationTokenUsingGETNotFound creates RefreshAndGetAuthenticationTokenUsingGETNotFound with default headers values
func NewRefreshAndGetAuthenticationTokenUsingGETNotFound() *RefreshAndGetAuthenticationTokenUsingGETNotFound {
	return &RefreshAndGetAuthenticationTokenUsingGETNotFound{}
}

// WriteResponse to the client
func (o *RefreshAndGetAuthenticationTokenUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
