// Code generated by go-swagger; DO NOT EDIT.

package data_source_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// AddDataSourceUsingPOSTOKCode is the HTTP code returned for type AddDataSourceUsingPOSTOK
const AddDataSourceUsingPOSTOKCode int = 200

/*AddDataSourceUsingPOSTOK OK

swagger:response addDataSourceUsingPOSTOK
*/
type AddDataSourceUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.DataSource `json:"body,omitempty"`
}

// NewAddDataSourceUsingPOSTOK creates AddDataSourceUsingPOSTOK with default headers values
func NewAddDataSourceUsingPOSTOK() *AddDataSourceUsingPOSTOK {
	return &AddDataSourceUsingPOSTOK{}
}

// WithPayload adds the payload to the add data source using p o s t o k response
func (o *AddDataSourceUsingPOSTOK) WithPayload(payload *models.DataSource) *AddDataSourceUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add data source using p o s t o k response
func (o *AddDataSourceUsingPOSTOK) SetPayload(payload *models.DataSource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddDataSourceUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddDataSourceUsingPOSTCreatedCode is the HTTP code returned for type AddDataSourceUsingPOSTCreated
const AddDataSourceUsingPOSTCreatedCode int = 201

/*AddDataSourceUsingPOSTCreated Created

swagger:response addDataSourceUsingPOSTCreated
*/
type AddDataSourceUsingPOSTCreated struct {
}

// NewAddDataSourceUsingPOSTCreated creates AddDataSourceUsingPOSTCreated with default headers values
func NewAddDataSourceUsingPOSTCreated() *AddDataSourceUsingPOSTCreated {
	return &AddDataSourceUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *AddDataSourceUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddDataSourceUsingPOSTUnauthorizedCode is the HTTP code returned for type AddDataSourceUsingPOSTUnauthorized
const AddDataSourceUsingPOSTUnauthorizedCode int = 401

/*AddDataSourceUsingPOSTUnauthorized Unauthorized

swagger:response addDataSourceUsingPOSTUnauthorized
*/
type AddDataSourceUsingPOSTUnauthorized struct {
}

// NewAddDataSourceUsingPOSTUnauthorized creates AddDataSourceUsingPOSTUnauthorized with default headers values
func NewAddDataSourceUsingPOSTUnauthorized() *AddDataSourceUsingPOSTUnauthorized {
	return &AddDataSourceUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *AddDataSourceUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddDataSourceUsingPOSTForbiddenCode is the HTTP code returned for type AddDataSourceUsingPOSTForbidden
const AddDataSourceUsingPOSTForbiddenCode int = 403

/*AddDataSourceUsingPOSTForbidden Forbidden

swagger:response addDataSourceUsingPOSTForbidden
*/
type AddDataSourceUsingPOSTForbidden struct {
}

// NewAddDataSourceUsingPOSTForbidden creates AddDataSourceUsingPOSTForbidden with default headers values
func NewAddDataSourceUsingPOSTForbidden() *AddDataSourceUsingPOSTForbidden {
	return &AddDataSourceUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *AddDataSourceUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddDataSourceUsingPOSTNotFoundCode is the HTTP code returned for type AddDataSourceUsingPOSTNotFound
const AddDataSourceUsingPOSTNotFoundCode int = 404

/*AddDataSourceUsingPOSTNotFound Not Found

swagger:response addDataSourceUsingPOSTNotFound
*/
type AddDataSourceUsingPOSTNotFound struct {
}

// NewAddDataSourceUsingPOSTNotFound creates AddDataSourceUsingPOSTNotFound with default headers values
func NewAddDataSourceUsingPOSTNotFound() *AddDataSourceUsingPOSTNotFound {
	return &AddDataSourceUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *AddDataSourceUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
