// Code generated by go-swagger; DO NOT EDIT.

package data_source_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// EditDataSourceUsingPUTOKCode is the HTTP code returned for type EditDataSourceUsingPUTOK
const EditDataSourceUsingPUTOKCode int = 200

/*EditDataSourceUsingPUTOK OK

swagger:response editDataSourceUsingPUTOK
*/
type EditDataSourceUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload *models.DataSource `json:"body,omitempty"`
}

// NewEditDataSourceUsingPUTOK creates EditDataSourceUsingPUTOK with default headers values
func NewEditDataSourceUsingPUTOK() *EditDataSourceUsingPUTOK {
	return &EditDataSourceUsingPUTOK{}
}

// WithPayload adds the payload to the edit data source using p u t o k response
func (o *EditDataSourceUsingPUTOK) WithPayload(payload *models.DataSource) *EditDataSourceUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit data source using p u t o k response
func (o *EditDataSourceUsingPUTOK) SetPayload(payload *models.DataSource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditDataSourceUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EditDataSourceUsingPUTCreatedCode is the HTTP code returned for type EditDataSourceUsingPUTCreated
const EditDataSourceUsingPUTCreatedCode int = 201

/*EditDataSourceUsingPUTCreated Created

swagger:response editDataSourceUsingPUTCreated
*/
type EditDataSourceUsingPUTCreated struct {
}

// NewEditDataSourceUsingPUTCreated creates EditDataSourceUsingPUTCreated with default headers values
func NewEditDataSourceUsingPUTCreated() *EditDataSourceUsingPUTCreated {
	return &EditDataSourceUsingPUTCreated{}
}

// WriteResponse to the client
func (o *EditDataSourceUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EditDataSourceUsingPUTUnauthorizedCode is the HTTP code returned for type EditDataSourceUsingPUTUnauthorized
const EditDataSourceUsingPUTUnauthorizedCode int = 401

/*EditDataSourceUsingPUTUnauthorized Unauthorized

swagger:response editDataSourceUsingPUTUnauthorized
*/
type EditDataSourceUsingPUTUnauthorized struct {
}

// NewEditDataSourceUsingPUTUnauthorized creates EditDataSourceUsingPUTUnauthorized with default headers values
func NewEditDataSourceUsingPUTUnauthorized() *EditDataSourceUsingPUTUnauthorized {
	return &EditDataSourceUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *EditDataSourceUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// EditDataSourceUsingPUTForbiddenCode is the HTTP code returned for type EditDataSourceUsingPUTForbidden
const EditDataSourceUsingPUTForbiddenCode int = 403

/*EditDataSourceUsingPUTForbidden Forbidden

swagger:response editDataSourceUsingPUTForbidden
*/
type EditDataSourceUsingPUTForbidden struct {
}

// NewEditDataSourceUsingPUTForbidden creates EditDataSourceUsingPUTForbidden with default headers values
func NewEditDataSourceUsingPUTForbidden() *EditDataSourceUsingPUTForbidden {
	return &EditDataSourceUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *EditDataSourceUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// EditDataSourceUsingPUTNotFoundCode is the HTTP code returned for type EditDataSourceUsingPUTNotFound
const EditDataSourceUsingPUTNotFoundCode int = 404

/*EditDataSourceUsingPUTNotFound Not Found

swagger:response editDataSourceUsingPUTNotFound
*/
type EditDataSourceUsingPUTNotFound struct {
}

// NewEditDataSourceUsingPUTNotFound creates EditDataSourceUsingPUTNotFound with default headers values
func NewEditDataSourceUsingPUTNotFound() *EditDataSourceUsingPUTNotFound {
	return &EditDataSourceUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *EditDataSourceUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
