// Code generated by go-swagger; DO NOT EDIT.

package data_source_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindRoleUsingGETParams creates a new FindRoleUsingGETParams object
// with the default values initialized.
func NewFindRoleUsingGETParams() FindRoleUsingGETParams {
	var ()
	return FindRoleUsingGETParams{}
}

// FindRoleUsingGETParams contains all the bound params for the find role using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters findRoleUsingGET
type FindRoleUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*datasourceId
	  Required: true
	  In: path
	*/
	DatasourceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindRoleUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rDatasourceID, rhkDatasourceID, _ := route.Params.GetOK("datasourceId")
	if err := o.bindDatasourceID(rDatasourceID, rhkDatasourceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindRoleUsingGETParams) bindDatasourceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DatasourceID = raw

	return nil
}
