// Code generated by go-swagger; DO NOT EDIT.

package data_source_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// FindRoleUsingGETOKCode is the HTTP code returned for type FindRoleUsingGETOK
const FindRoleUsingGETOKCode int = 200

/*FindRoleUsingGETOK OK

swagger:response findRoleUsingGETOK
*/
type FindRoleUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.DataSource `json:"body,omitempty"`
}

// NewFindRoleUsingGETOK creates FindRoleUsingGETOK with default headers values
func NewFindRoleUsingGETOK() *FindRoleUsingGETOK {
	return &FindRoleUsingGETOK{}
}

// WithPayload adds the payload to the find role using g e t o k response
func (o *FindRoleUsingGETOK) WithPayload(payload *models.DataSource) *FindRoleUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find role using g e t o k response
func (o *FindRoleUsingGETOK) SetPayload(payload *models.DataSource) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindRoleUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindRoleUsingGETUnauthorizedCode is the HTTP code returned for type FindRoleUsingGETUnauthorized
const FindRoleUsingGETUnauthorizedCode int = 401

/*FindRoleUsingGETUnauthorized Unauthorized

swagger:response findRoleUsingGETUnauthorized
*/
type FindRoleUsingGETUnauthorized struct {
}

// NewFindRoleUsingGETUnauthorized creates FindRoleUsingGETUnauthorized with default headers values
func NewFindRoleUsingGETUnauthorized() *FindRoleUsingGETUnauthorized {
	return &FindRoleUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindRoleUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindRoleUsingGETForbiddenCode is the HTTP code returned for type FindRoleUsingGETForbidden
const FindRoleUsingGETForbiddenCode int = 403

/*FindRoleUsingGETForbidden Forbidden

swagger:response findRoleUsingGETForbidden
*/
type FindRoleUsingGETForbidden struct {
}

// NewFindRoleUsingGETForbidden creates FindRoleUsingGETForbidden with default headers values
func NewFindRoleUsingGETForbidden() *FindRoleUsingGETForbidden {
	return &FindRoleUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindRoleUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindRoleUsingGETNotFoundCode is the HTTP code returned for type FindRoleUsingGETNotFound
const FindRoleUsingGETNotFoundCode int = 404

/*FindRoleUsingGETNotFound Not Found

swagger:response findRoleUsingGETNotFound
*/
type FindRoleUsingGETNotFound struct {
}

// NewFindRoleUsingGETNotFound creates FindRoleUsingGETNotFound with default headers values
func NewFindRoleUsingGETNotFound() *FindRoleUsingGETNotFound {
	return &FindRoleUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindRoleUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
