// Code generated by go-swagger; DO NOT EDIT.

package data_source_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListUsingGETParams creates a new ListUsingGETParams object
// with the default values initialized.
func NewListUsingGETParams() ListUsingGETParams {
	var ()
	return ListUsingGETParams{}
}

// ListUsingGETParams contains all the bound params for the list using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters listUsingGET
type ListUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ListUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
