// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi DataHive RESTful APIs

    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
