// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ChoiceItem choice item
// swagger:model ChoiceItem
//go:generate gormgen -structs ChoiceItem -output choice_item_gorm.go
type ChoiceItem struct {

	// id
	ID string `gorm:"primary_key;AUTO_INCREMENT" json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty" form:"name"`
}

// Validate validates this choice item
func (m *ChoiceItem) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ChoiceItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChoiceItem) UnmarshalBinary(b []byte) error {
	var res ChoiceItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
