// Code generated by go-swagger; DO NOT EDIT.

package data_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DataQueryUsingGETOKCode is the HTTP code returned for type DataQueryUsingGETOK
const DataQueryUsingGETOKCode int = 200

/*DataQueryUsingGETOK OK

swagger:response dataQueryUsingGETOK
*/
type DataQueryUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload DataQueryUsingGETOKBody `json:"body,omitempty"`
}

// NewDataQueryUsingGETOK creates DataQueryUsingGETOK with default headers values
func NewDataQueryUsingGETOK() *DataQueryUsingGETOK {
	return &DataQueryUsingGETOK{}
}

// WithPayload adds the payload to the data query using g e t o k response
func (o *DataQueryUsingGETOK) WithPayload(payload DataQueryUsingGETOKBody) *DataQueryUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the data query using g e t o k response
func (o *DataQueryUsingGETOK) SetPayload(payload DataQueryUsingGETOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DataQueryUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DataQueryUsingGETUnauthorizedCode is the HTTP code returned for type DataQueryUsingGETUnauthorized
const DataQueryUsingGETUnauthorizedCode int = 401

/*DataQueryUsingGETUnauthorized Unauthorized

swagger:response dataQueryUsingGETUnauthorized
*/
type DataQueryUsingGETUnauthorized struct {
}

// NewDataQueryUsingGETUnauthorized creates DataQueryUsingGETUnauthorized with default headers values
func NewDataQueryUsingGETUnauthorized() *DataQueryUsingGETUnauthorized {
	return &DataQueryUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *DataQueryUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DataQueryUsingGETForbiddenCode is the HTTP code returned for type DataQueryUsingGETForbidden
const DataQueryUsingGETForbiddenCode int = 403

/*DataQueryUsingGETForbidden Forbidden

swagger:response dataQueryUsingGETForbidden
*/
type DataQueryUsingGETForbidden struct {
}

// NewDataQueryUsingGETForbidden creates DataQueryUsingGETForbidden with default headers values
func NewDataQueryUsingGETForbidden() *DataQueryUsingGETForbidden {
	return &DataQueryUsingGETForbidden{}
}

// WriteResponse to the client
func (o *DataQueryUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DataQueryUsingGETNotFoundCode is the HTTP code returned for type DataQueryUsingGETNotFound
const DataQueryUsingGETNotFoundCode int = 404

/*DataQueryUsingGETNotFound Not Found

swagger:response dataQueryUsingGETNotFound
*/
type DataQueryUsingGETNotFound struct {
}

// NewDataQueryUsingGETNotFound creates DataQueryUsingGETNotFound with default headers values
func NewDataQueryUsingGETNotFound() *DataQueryUsingGETNotFound {
	return &DataQueryUsingGETNotFound{}
}

// WriteResponse to the client
func (o *DataQueryUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
