// Code generated by go-swagger; DO NOT EDIT.

package data_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DataMutationUsingPUTOKCode is the HTTP code returned for type DataMutationUsingPUTOK
const DataMutationUsingPUTOKCode int = 200

/*DataMutationUsingPUTOK OK

swagger:response dataMutationUsingPUTOK
*/
type DataMutationUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload DataMutationUsingPUTOKBody `json:"body,omitempty"`
}

// NewDataMutationUsingPUTOK creates DataMutationUsingPUTOK with default headers values
func NewDataMutationUsingPUTOK() *DataMutationUsingPUTOK {
	return &DataMutationUsingPUTOK{}
}

// WithPayload adds the payload to the data mutation using p u t o k response
func (o *DataMutationUsingPUTOK) WithPayload(payload DataMutationUsingPUTOKBody) *DataMutationUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the data mutation using p u t o k response
func (o *DataMutationUsingPUTOK) SetPayload(payload DataMutationUsingPUTOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DataMutationUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DataMutationUsingPUTCreatedCode is the HTTP code returned for type DataMutationUsingPUTCreated
const DataMutationUsingPUTCreatedCode int = 201

/*DataMutationUsingPUTCreated Created

swagger:response dataMutationUsingPUTCreated
*/
type DataMutationUsingPUTCreated struct {
}

// NewDataMutationUsingPUTCreated creates DataMutationUsingPUTCreated with default headers values
func NewDataMutationUsingPUTCreated() *DataMutationUsingPUTCreated {
	return &DataMutationUsingPUTCreated{}
}

// WriteResponse to the client
func (o *DataMutationUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// DataMutationUsingPUTUnauthorizedCode is the HTTP code returned for type DataMutationUsingPUTUnauthorized
const DataMutationUsingPUTUnauthorizedCode int = 401

/*DataMutationUsingPUTUnauthorized Unauthorized

swagger:response dataMutationUsingPUTUnauthorized
*/
type DataMutationUsingPUTUnauthorized struct {
}

// NewDataMutationUsingPUTUnauthorized creates DataMutationUsingPUTUnauthorized with default headers values
func NewDataMutationUsingPUTUnauthorized() *DataMutationUsingPUTUnauthorized {
	return &DataMutationUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *DataMutationUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DataMutationUsingPUTForbiddenCode is the HTTP code returned for type DataMutationUsingPUTForbidden
const DataMutationUsingPUTForbiddenCode int = 403

/*DataMutationUsingPUTForbidden Forbidden

swagger:response dataMutationUsingPUTForbidden
*/
type DataMutationUsingPUTForbidden struct {
}

// NewDataMutationUsingPUTForbidden creates DataMutationUsingPUTForbidden with default headers values
func NewDataMutationUsingPUTForbidden() *DataMutationUsingPUTForbidden {
	return &DataMutationUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *DataMutationUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DataMutationUsingPUTNotFoundCode is the HTTP code returned for type DataMutationUsingPUTNotFound
const DataMutationUsingPUTNotFoundCode int = 404

/*DataMutationUsingPUTNotFound Not Found

swagger:response dataMutationUsingPUTNotFound
*/
type DataMutationUsingPUTNotFound struct {
}

// NewDataMutationUsingPUTNotFound creates DataMutationUsingPUTNotFound with default headers values
func NewDataMutationUsingPUTNotFound() *DataMutationUsingPUTNotFound {
	return &DataMutationUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *DataMutationUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
