// Code generated by go-swagger; DO NOT EDIT.

package data_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	validate "github.com/go-openapi/validate"
)

// DataMutationUsingPUTHandlerFunc turns a function with the right signature into a data mutation using p u t handler
type DataMutationUsingPUTHandlerFunc func(DataMutationUsingPUTParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DataMutationUsingPUTHandlerFunc) Handle(params DataMutationUsingPUTParams) middleware.Responder {
	return fn(params)
}

// DataMutationUsingPUTHandler interface for that can handle valid data mutation using p u t params
type DataMutationUsingPUTHandler interface {
	Handle(DataMutationUsingPUTParams) middleware.Responder
}

// NewDataMutationUsingPUT creates a new http.Handler for the data mutation using p u t operation
func NewDataMutationUsingPUT(ctx *middleware.Context, handler DataMutationUsingPUTHandler) *DataMutationUsingPUT {
	return &DataMutationUsingPUT{Context: ctx, Handler: handler}
}

/*DataMutationUsingPUT swagger:route PUT /api/{entity}/{id} data-controller dataMutationUsingPUT

dataMutation

*/
type DataMutationUsingPUT struct {
	Context *middleware.Context
	Handler DataMutationUsingPUTHandler
}

func (o *DataMutationUsingPUT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDataMutationUsingPUTParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DataMutationUsingPUTOKBody data mutation using p u t o k body
// swagger:model DataMutationUsingPUTOKBody
type DataMutationUsingPUTOKBody map[string]interface{}

// Validate validates this data mutation using p u t o k body
func (o DataMutationUsingPUTOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("dataMutationUsingPUTOK", "body", o); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
