// Code generated by go-swagger; DO NOT EDIT.

package data_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DataMutationUsingDELETEOKCode is the HTTP code returned for type DataMutationUsingDELETEOK
const DataMutationUsingDELETEOKCode int = 200

/*DataMutationUsingDELETEOK OK

swagger:response dataMutationUsingDELETEOK
*/
type DataMutationUsingDELETEOK struct {

	/*
	  In: Body
	*/
	Payload DataMutationUsingDELETEOKBody `json:"body,omitempty"`
}

// NewDataMutationUsingDELETEOK creates DataMutationUsingDELETEOK with default headers values
func NewDataMutationUsingDELETEOK() *DataMutationUsingDELETEOK {
	return &DataMutationUsingDELETEOK{}
}

// WithPayload adds the payload to the data mutation using d e l e t e o k response
func (o *DataMutationUsingDELETEOK) WithPayload(payload DataMutationUsingDELETEOKBody) *DataMutationUsingDELETEOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the data mutation using d e l e t e o k response
func (o *DataMutationUsingDELETEOK) SetPayload(payload DataMutationUsingDELETEOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DataMutationUsingDELETEOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// DataMutationUsingDELETENoContentCode is the HTTP code returned for type DataMutationUsingDELETENoContent
const DataMutationUsingDELETENoContentCode int = 204

/*DataMutationUsingDELETENoContent No Content

swagger:response dataMutationUsingDELETENoContent
*/
type DataMutationUsingDELETENoContent struct {
}

// NewDataMutationUsingDELETENoContent creates DataMutationUsingDELETENoContent with default headers values
func NewDataMutationUsingDELETENoContent() *DataMutationUsingDELETENoContent {
	return &DataMutationUsingDELETENoContent{}
}

// WriteResponse to the client
func (o *DataMutationUsingDELETENoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DataMutationUsingDELETEUnauthorizedCode is the HTTP code returned for type DataMutationUsingDELETEUnauthorized
const DataMutationUsingDELETEUnauthorizedCode int = 401

/*DataMutationUsingDELETEUnauthorized Unauthorized

swagger:response dataMutationUsingDELETEUnauthorized
*/
type DataMutationUsingDELETEUnauthorized struct {
}

// NewDataMutationUsingDELETEUnauthorized creates DataMutationUsingDELETEUnauthorized with default headers values
func NewDataMutationUsingDELETEUnauthorized() *DataMutationUsingDELETEUnauthorized {
	return &DataMutationUsingDELETEUnauthorized{}
}

// WriteResponse to the client
func (o *DataMutationUsingDELETEUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DataMutationUsingDELETEForbiddenCode is the HTTP code returned for type DataMutationUsingDELETEForbidden
const DataMutationUsingDELETEForbiddenCode int = 403

/*DataMutationUsingDELETEForbidden Forbidden

swagger:response dataMutationUsingDELETEForbidden
*/
type DataMutationUsingDELETEForbidden struct {
}

// NewDataMutationUsingDELETEForbidden creates DataMutationUsingDELETEForbidden with default headers values
func NewDataMutationUsingDELETEForbidden() *DataMutationUsingDELETEForbidden {
	return &DataMutationUsingDELETEForbidden{}
}

// WriteResponse to the client
func (o *DataMutationUsingDELETEForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
