// Code generated by go-swagger; DO NOT EDIT.

package data_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindOneUsingGETOKCode is the HTTP code returned for type FindOneUsingGETOK
const FindOneUsingGETOKCode int = 200

/*FindOneUsingGETOK OK

swagger:response findOneUsingGETOK
*/
type FindOneUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload FindOneUsingGETOKBody `json:"body,omitempty"`
}

// NewFindOneUsingGETOK creates FindOneUsingGETOK with default headers values
func NewFindOneUsingGETOK() *FindOneUsingGETOK {
	return &FindOneUsingGETOK{}
}

// WithPayload adds the payload to the find one using g e t o k response
func (o *FindOneUsingGETOK) WithPayload(payload FindOneUsingGETOKBody) *FindOneUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find one using g e t o k response
func (o *FindOneUsingGETOK) SetPayload(payload FindOneUsingGETOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindOneUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindOneUsingGETUnauthorizedCode is the HTTP code returned for type FindOneUsingGETUnauthorized
const FindOneUsingGETUnauthorizedCode int = 401

/*FindOneUsingGETUnauthorized Unauthorized

swagger:response findOneUsingGETUnauthorized
*/
type FindOneUsingGETUnauthorized struct {
}

// NewFindOneUsingGETUnauthorized creates FindOneUsingGETUnauthorized with default headers values
func NewFindOneUsingGETUnauthorized() *FindOneUsingGETUnauthorized {
	return &FindOneUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindOneUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindOneUsingGETForbiddenCode is the HTTP code returned for type FindOneUsingGETForbidden
const FindOneUsingGETForbiddenCode int = 403

/*FindOneUsingGETForbidden Forbidden

swagger:response findOneUsingGETForbidden
*/
type FindOneUsingGETForbidden struct {
}

// NewFindOneUsingGETForbidden creates FindOneUsingGETForbidden with default headers values
func NewFindOneUsingGETForbidden() *FindOneUsingGETForbidden {
	return &FindOneUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindOneUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindOneUsingGETNotFoundCode is the HTTP code returned for type FindOneUsingGETNotFound
const FindOneUsingGETNotFoundCode int = 404

/*FindOneUsingGETNotFound Not Found

swagger:response findOneUsingGETNotFound
*/
type FindOneUsingGETNotFound struct {
}

// NewFindOneUsingGETNotFound creates FindOneUsingGETNotFound with default headers values
func NewFindOneUsingGETNotFound() *FindOneUsingGETNotFound {
	return &FindOneUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindOneUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
