// Code generated by go-swagger; DO NOT EDIT.

package data_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	validate "github.com/go-openapi/validate"
)

// FindOneUsingGETHandlerFunc turns a function with the right signature into a find one using g e t handler
type FindOneUsingGETHandlerFunc func(FindOneUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindOneUsingGETHandlerFunc) Handle(params FindOneUsingGETParams) middleware.Responder {
	return fn(params)
}

// FindOneUsingGETHandler interface for that can handle valid find one using g e t params
type FindOneUsingGETHandler interface {
	Handle(FindOneUsingGETParams) middleware.Responder
}

// NewFindOneUsingGET creates a new http.Handler for the find one using g e t operation
func NewFindOneUsingGET(ctx *middleware.Context, handler FindOneUsingGETHandler) *FindOneUsingGET {
	return &FindOneUsingGET{Context: ctx, Handler: handler}
}

/*FindOneUsingGET swagger:route GET /api/{entity}/{id} data-controller findOneUsingGET

findOne

*/
type FindOneUsingGET struct {
	Context *middleware.Context
	Handler FindOneUsingGETHandler
}

func (o *FindOneUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindOneUsingGETParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// FindOneUsingGETOKBody find one using g e t o k body
// swagger:model FindOneUsingGETOKBody
type FindOneUsingGETOKBody map[string]interface{}

// Validate validates this find one using g e t o k body
func (o FindOneUsingGETOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("findOneUsingGETOK", "body", o); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
