// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// NewAddEntityUsingPOSTParams creates a new AddEntityUsingPOSTParams object
// with the default values initialized.
func NewAddEntityUsingPOSTParams() AddEntityUsingPOSTParams {
	var ()
	return AddEntityUsingPOSTParams{}
}

// AddEntityUsingPOSTParams contains all the bound params for the add entity using p o s t operation
// typically these are obtained from a http.Request
//
// swagger:parameters addEntityUsingPOST
type AddEntityUsingPOSTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*entity
	  Required: true
	  In: body
	*/
	Entity *models.Entity
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AddEntityUsingPOSTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Entity
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("entity", "body"))
			} else {
				res = append(res, errors.NewParseError("entity", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Entity = &body
			}
		}

	} else {
		res = append(res, errors.Required("entity", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
