// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// AddEntityUsingPOSTOKCode is the HTTP code returned for type AddEntityUsingPOSTOK
const AddEntityUsingPOSTOKCode int = 200

/*AddEntityUsingPOSTOK OK

swagger:response addEntityUsingPOSTOK
*/
type AddEntityUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Entity `json:"body,omitempty"`
}

// NewAddEntityUsingPOSTOK creates AddEntityUsingPOSTOK with default headers values
func NewAddEntityUsingPOSTOK() *AddEntityUsingPOSTOK {
	return &AddEntityUsingPOSTOK{}
}

// WithPayload adds the payload to the add entity using p o s t o k response
func (o *AddEntityUsingPOSTOK) WithPayload(payload *models.Entity) *AddEntityUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add entity using p o s t o k response
func (o *AddEntityUsingPOSTOK) SetPayload(payload *models.Entity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddEntityUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddEntityUsingPOSTCreatedCode is the HTTP code returned for type AddEntityUsingPOSTCreated
const AddEntityUsingPOSTCreatedCode int = 201

/*AddEntityUsingPOSTCreated Created

swagger:response addEntityUsingPOSTCreated
*/
type AddEntityUsingPOSTCreated struct {
}

// NewAddEntityUsingPOSTCreated creates AddEntityUsingPOSTCreated with default headers values
func NewAddEntityUsingPOSTCreated() *AddEntityUsingPOSTCreated {
	return &AddEntityUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *AddEntityUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddEntityUsingPOSTUnauthorizedCode is the HTTP code returned for type AddEntityUsingPOSTUnauthorized
const AddEntityUsingPOSTUnauthorizedCode int = 401

/*AddEntityUsingPOSTUnauthorized Unauthorized

swagger:response addEntityUsingPOSTUnauthorized
*/
type AddEntityUsingPOSTUnauthorized struct {
}

// NewAddEntityUsingPOSTUnauthorized creates AddEntityUsingPOSTUnauthorized with default headers values
func NewAddEntityUsingPOSTUnauthorized() *AddEntityUsingPOSTUnauthorized {
	return &AddEntityUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *AddEntityUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddEntityUsingPOSTForbiddenCode is the HTTP code returned for type AddEntityUsingPOSTForbidden
const AddEntityUsingPOSTForbiddenCode int = 403

/*AddEntityUsingPOSTForbidden Forbidden

swagger:response addEntityUsingPOSTForbidden
*/
type AddEntityUsingPOSTForbidden struct {
}

// NewAddEntityUsingPOSTForbidden creates AddEntityUsingPOSTForbidden with default headers values
func NewAddEntityUsingPOSTForbidden() *AddEntityUsingPOSTForbidden {
	return &AddEntityUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *AddEntityUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddEntityUsingPOSTNotFoundCode is the HTTP code returned for type AddEntityUsingPOSTNotFound
const AddEntityUsingPOSTNotFoundCode int = 404

/*AddEntityUsingPOSTNotFound Not Found

swagger:response addEntityUsingPOSTNotFound
*/
type AddEntityUsingPOSTNotFound struct {
}

// NewAddEntityUsingPOSTNotFound creates AddEntityUsingPOSTNotFound with default headers values
func NewAddEntityUsingPOSTNotFound() *AddEntityUsingPOSTNotFound {
	return &AddEntityUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *AddEntityUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
