// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// AddFieldUsingPOSTOKCode is the HTTP code returned for type AddFieldUsingPOSTOK
const AddFieldUsingPOSTOKCode int = 200

/*AddFieldUsingPOSTOK OK

swagger:response addFieldUsingPOSTOK
*/
type AddFieldUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Field `json:"body,omitempty"`
}

// NewAddFieldUsingPOSTOK creates AddFieldUsingPOSTOK with default headers values
func NewAddFieldUsingPOSTOK() *AddFieldUsingPOSTOK {
	return &AddFieldUsingPOSTOK{}
}

// WithPayload adds the payload to the add field using p o s t o k response
func (o *AddFieldUsingPOSTOK) WithPayload(payload *models.Field) *AddFieldUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add field using p o s t o k response
func (o *AddFieldUsingPOSTOK) SetPayload(payload *models.Field) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddFieldUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddFieldUsingPOSTCreatedCode is the HTTP code returned for type AddFieldUsingPOSTCreated
const AddFieldUsingPOSTCreatedCode int = 201

/*AddFieldUsingPOSTCreated Created

swagger:response addFieldUsingPOSTCreated
*/
type AddFieldUsingPOSTCreated struct {
}

// NewAddFieldUsingPOSTCreated creates AddFieldUsingPOSTCreated with default headers values
func NewAddFieldUsingPOSTCreated() *AddFieldUsingPOSTCreated {
	return &AddFieldUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *AddFieldUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddFieldUsingPOSTUnauthorizedCode is the HTTP code returned for type AddFieldUsingPOSTUnauthorized
const AddFieldUsingPOSTUnauthorizedCode int = 401

/*AddFieldUsingPOSTUnauthorized Unauthorized

swagger:response addFieldUsingPOSTUnauthorized
*/
type AddFieldUsingPOSTUnauthorized struct {
}

// NewAddFieldUsingPOSTUnauthorized creates AddFieldUsingPOSTUnauthorized with default headers values
func NewAddFieldUsingPOSTUnauthorized() *AddFieldUsingPOSTUnauthorized {
	return &AddFieldUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *AddFieldUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddFieldUsingPOSTForbiddenCode is the HTTP code returned for type AddFieldUsingPOSTForbidden
const AddFieldUsingPOSTForbiddenCode int = 403

/*AddFieldUsingPOSTForbidden Forbidden

swagger:response addFieldUsingPOSTForbidden
*/
type AddFieldUsingPOSTForbidden struct {
}

// NewAddFieldUsingPOSTForbidden creates AddFieldUsingPOSTForbidden with default headers values
func NewAddFieldUsingPOSTForbidden() *AddFieldUsingPOSTForbidden {
	return &AddFieldUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *AddFieldUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddFieldUsingPOSTNotFoundCode is the HTTP code returned for type AddFieldUsingPOSTNotFound
const AddFieldUsingPOSTNotFoundCode int = 404

/*AddFieldUsingPOSTNotFound Not Found

swagger:response addFieldUsingPOSTNotFound
*/
type AddFieldUsingPOSTNotFound struct {
}

// NewAddFieldUsingPOSTNotFound creates AddFieldUsingPOSTNotFound with default headers values
func NewAddFieldUsingPOSTNotFound() *AddFieldUsingPOSTNotFound {
	return &AddFieldUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *AddFieldUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
