// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// EditEntityUsingPUTOKCode is the HTTP code returned for type EditEntityUsingPUTOK
const EditEntityUsingPUTOKCode int = 200

/*EditEntityUsingPUTOK OK

swagger:response editEntityUsingPUTOK
*/
type EditEntityUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Entity `json:"body,omitempty"`
}

// NewEditEntityUsingPUTOK creates EditEntityUsingPUTOK with default headers values
func NewEditEntityUsingPUTOK() *EditEntityUsingPUTOK {
	return &EditEntityUsingPUTOK{}
}

// WithPayload adds the payload to the edit entity using p u t o k response
func (o *EditEntityUsingPUTOK) WithPayload(payload *models.Entity) *EditEntityUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit entity using p u t o k response
func (o *EditEntityUsingPUTOK) SetPayload(payload *models.Entity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditEntityUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EditEntityUsingPUTCreatedCode is the HTTP code returned for type EditEntityUsingPUTCreated
const EditEntityUsingPUTCreatedCode int = 201

/*EditEntityUsingPUTCreated Created

swagger:response editEntityUsingPUTCreated
*/
type EditEntityUsingPUTCreated struct {
}

// NewEditEntityUsingPUTCreated creates EditEntityUsingPUTCreated with default headers values
func NewEditEntityUsingPUTCreated() *EditEntityUsingPUTCreated {
	return &EditEntityUsingPUTCreated{}
}

// WriteResponse to the client
func (o *EditEntityUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EditEntityUsingPUTUnauthorizedCode is the HTTP code returned for type EditEntityUsingPUTUnauthorized
const EditEntityUsingPUTUnauthorizedCode int = 401

/*EditEntityUsingPUTUnauthorized Unauthorized

swagger:response editEntityUsingPUTUnauthorized
*/
type EditEntityUsingPUTUnauthorized struct {
}

// NewEditEntityUsingPUTUnauthorized creates EditEntityUsingPUTUnauthorized with default headers values
func NewEditEntityUsingPUTUnauthorized() *EditEntityUsingPUTUnauthorized {
	return &EditEntityUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *EditEntityUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// EditEntityUsingPUTForbiddenCode is the HTTP code returned for type EditEntityUsingPUTForbidden
const EditEntityUsingPUTForbiddenCode int = 403

/*EditEntityUsingPUTForbidden Forbidden

swagger:response editEntityUsingPUTForbidden
*/
type EditEntityUsingPUTForbidden struct {
}

// NewEditEntityUsingPUTForbidden creates EditEntityUsingPUTForbidden with default headers values
func NewEditEntityUsingPUTForbidden() *EditEntityUsingPUTForbidden {
	return &EditEntityUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *EditEntityUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// EditEntityUsingPUTNotFoundCode is the HTTP code returned for type EditEntityUsingPUTNotFound
const EditEntityUsingPUTNotFoundCode int = 404

/*EditEntityUsingPUTNotFound Not Found

swagger:response editEntityUsingPUTNotFound
*/
type EditEntityUsingPUTNotFound struct {
}

// NewEditEntityUsingPUTNotFound creates EditEntityUsingPUTNotFound with default headers values
func NewEditEntityUsingPUTNotFound() *EditEntityUsingPUTNotFound {
	return &EditEntityUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *EditEntityUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
