// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// NewEditEntityUsingPUTParams creates a new EditEntityUsingPUTParams object
// with the default values initialized.
func NewEditEntityUsingPUTParams() EditEntityUsingPUTParams {
	var ()
	return EditEntityUsingPUTParams{}
}

// EditEntityUsingPUTParams contains all the bound params for the edit entity using p u t operation
// typically these are obtained from a http.Request
//
// swagger:parameters editEntityUsingPUT
type EditEntityUsingPUTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*entity
	  Required: true
	  In: body
	*/
	Entity *models.Entity
	/*id
	  Required: true
	  In: path
	*/
	ID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *EditEntityUsingPUTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Entity
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("entity", "body"))
			} else {
				res = append(res, errors.NewParseError("entity", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Entity = &body
			}
		}

	} else {
		res = append(res, errors.Required("entity", "body"))
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *EditEntityUsingPUTParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ID = raw

	return nil
}
