// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// EditFieldUsingPUTOKCode is the HTTP code returned for type EditFieldUsingPUTOK
const EditFieldUsingPUTOKCode int = 200

/*EditFieldUsingPUTOK OK

swagger:response editFieldUsingPUTOK
*/
type EditFieldUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Field `json:"body,omitempty"`
}

// NewEditFieldUsingPUTOK creates EditFieldUsingPUTOK with default headers values
func NewEditFieldUsingPUTOK() *EditFieldUsingPUTOK {
	return &EditFieldUsingPUTOK{}
}

// WithPayload adds the payload to the edit field using p u t o k response
func (o *EditFieldUsingPUTOK) WithPayload(payload *models.Field) *EditFieldUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the edit field using p u t o k response
func (o *EditFieldUsingPUTOK) SetPayload(payload *models.Field) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *EditFieldUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// EditFieldUsingPUTCreatedCode is the HTTP code returned for type EditFieldUsingPUTCreated
const EditFieldUsingPUTCreatedCode int = 201

/*EditFieldUsingPUTCreated Created

swagger:response editFieldUsingPUTCreated
*/
type EditFieldUsingPUTCreated struct {
}

// NewEditFieldUsingPUTCreated creates EditFieldUsingPUTCreated with default headers values
func NewEditFieldUsingPUTCreated() *EditFieldUsingPUTCreated {
	return &EditFieldUsingPUTCreated{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// EditFieldUsingPUTUnauthorizedCode is the HTTP code returned for type EditFieldUsingPUTUnauthorized
const EditFieldUsingPUTUnauthorizedCode int = 401

/*EditFieldUsingPUTUnauthorized Unauthorized

swagger:response editFieldUsingPUTUnauthorized
*/
type EditFieldUsingPUTUnauthorized struct {
}

// NewEditFieldUsingPUTUnauthorized creates EditFieldUsingPUTUnauthorized with default headers values
func NewEditFieldUsingPUTUnauthorized() *EditFieldUsingPUTUnauthorized {
	return &EditFieldUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// EditFieldUsingPUTForbiddenCode is the HTTP code returned for type EditFieldUsingPUTForbidden
const EditFieldUsingPUTForbiddenCode int = 403

/*EditFieldUsingPUTForbidden Forbidden

swagger:response editFieldUsingPUTForbidden
*/
type EditFieldUsingPUTForbidden struct {
}

// NewEditFieldUsingPUTForbidden creates EditFieldUsingPUTForbidden with default headers values
func NewEditFieldUsingPUTForbidden() *EditFieldUsingPUTForbidden {
	return &EditFieldUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// EditFieldUsingPUTNotFoundCode is the HTTP code returned for type EditFieldUsingPUTNotFound
const EditFieldUsingPUTNotFoundCode int = 404

/*EditFieldUsingPUTNotFound Not Found

swagger:response editFieldUsingPUTNotFound
*/
type EditFieldUsingPUTNotFound struct {
}

// NewEditFieldUsingPUTNotFound creates EditFieldUsingPUTNotFound with default headers values
func NewEditFieldUsingPUTNotFound() *EditFieldUsingPUTNotFound {
	return &EditFieldUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *EditFieldUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
