// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindEntityFieldsUsingGETParams creates a new FindEntityFieldsUsingGETParams object
// with the default values initialized.
func NewFindEntityFieldsUsingGETParams() FindEntityFieldsUsingGETParams {
	var ()
	return FindEntityFieldsUsingGETParams{}
}

// FindEntityFieldsUsingGETParams contains all the bound params for the find entity fields using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters findEntityFieldsUsingGET
type FindEntityFieldsUsingGETParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*entityName
	  Required: true
	  In: query
	*/
	EntityName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindEntityFieldsUsingGETParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qEntityName, qhkEntityName, _ := qs.GetOK("entityName")
	if err := o.bindEntityName(qEntityName, qhkEntityName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindEntityFieldsUsingGETParams) bindEntityName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("entityName", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("entityName", "query", raw); err != nil {
		return err
	}

	o.EntityName = raw

	return nil
}
