package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"
	"github.com/roscopecoltran/admin-on-rest-server/server/api"

	strfmt "github.com/go-openapi/strfmt"
)

// BusinessLogicFindEntityFieldsUsingGET executes the core logic of the related
// route endpoint.
func BusinessLogicFindEntityFieldsUsingGET(f func(ctx *gin.Context, params *FindEntityFieldsUsingGETParams) *api.Response) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		// generate params from request
		params := &FindEntityFieldsUsingGETParams{}
		err := params.bindRequest(ctx)
		if err != nil {
			errObj := err.(*errors.CompositeError)
			problem := api.Problem{
				Title:  "Unprocessable Entity.",
				Status: int(errObj.Code()),
				Detail: errObj.Error(),
			}
			ctx.Writer.Header().Set("Content-Type", "application/problem+json")
			ctx.JSON(problem.Status, problem)
			return
		}

		resp := f(ctx, params)
		switch resp.Code {
		case http.StatusNoContent:
			ctx.AbortWithStatus(resp.Code)
		default:
			ctx.JSON(resp.Code, resp.Body)
		}
	}
}

// FindEntityFieldsUsingGETParams contains all the bound params for the find entity fields using g e t operation
// typically these are obtained from a http.Request
//
// swagger:parameters findEntityFieldsUsingGET
type FindEntityFieldsUsingGETParams struct {

	/*entityName
	  Required: true
	  In: query
	*/
	EntityName string
}

// FindEntityFieldsUsingGETParamsFromCtx gets the params struct from the gin context.
func FindEntityFieldsUsingGETParamsFromCtx(ctx *gin.Context) *FindEntityFieldsUsingGETParams {
	params, _ := ctx.Get("params")
	return params.(*FindEntityFieldsUsingGETParams)
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindEntityFieldsUsingGETParams) bindRequest(ctx *gin.Context) error {
	var res []error
	formats := strfmt.NewFormats()

	qs := runtime.Values(ctx.Request.URL.Query())

	qEntityName, qhkEntityName, _ := qs.GetOK("entityName")
	if err := o.bindEntityName(qEntityName, qhkEntityName, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindEntityFieldsUsingGETParams) bindEntityName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("entityName", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("entityName", "query", raw); err != nil {
		return err
	}

	o.EntityName = raw

	return nil
}

// vim: ft=go
