package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/go-openapi/errors"
	"github.com/roscopecoltran/admin-on-rest-server/server/api"

	strfmt "github.com/go-openapi/strfmt"
)

// BusinessLogicFindOneUsingGET1 executes the core logic of the related
// route endpoint.
func BusinessLogicFindOneUsingGET1(f func(ctx *gin.Context, params *FindOneUsingGET1Params) *api.Response) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		// generate params from request
		params := &FindOneUsingGET1Params{}
		err := params.bindRequest(ctx)
		if err != nil {
			errObj := err.(*errors.CompositeError)
			problem := api.Problem{
				Title:  "Unprocessable Entity.",
				Status: int(errObj.Code()),
				Detail: errObj.Error(),
			}
			ctx.Writer.Header().Set("Content-Type", "application/problem+json")
			ctx.JSON(problem.Status, problem)
			return
		}

		resp := f(ctx, params)
		switch resp.Code {
		case http.StatusNoContent:
			ctx.AbortWithStatus(resp.Code)
		default:
			ctx.JSON(resp.Code, resp.Body)
		}
	}
}

// FindOneUsingGET1Params contains all the bound params for the find one using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters findOneUsingGET_1
type FindOneUsingGET1Params struct {

	/*eid
	  Required: true
	  In: path
	*/
	Eid string
}

// FindOneUsingGET1ParamsFromCtx gets the params struct from the gin context.
func FindOneUsingGET1ParamsFromCtx(ctx *gin.Context) *FindOneUsingGET1Params {
	params, _ := ctx.Get("params")
	return params.(*FindOneUsingGET1Params)
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindOneUsingGET1Params) bindRequest(ctx *gin.Context) error {
	var res []error
	formats := strfmt.NewFormats()

	rEid := []string{ctx.Param("eid")}
	if err := o.bindEid(rEid, true, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindOneUsingGET1Params) bindEid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Eid = raw

	return nil
}

// vim: ft=go
