// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// FindEntityFieldsUsingGETOKCode is the HTTP code returned for type FindEntityFieldsUsingGETOK
const FindEntityFieldsUsingGETOKCode int = 200

/*FindEntityFieldsUsingGETOK OK

swagger:response findEntityFieldsUsingGETOK
*/
type FindEntityFieldsUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Field `json:"body,omitempty"`
}

// NewFindEntityFieldsUsingGETOK creates FindEntityFieldsUsingGETOK with default headers values
func NewFindEntityFieldsUsingGETOK() *FindEntityFieldsUsingGETOK {
	return &FindEntityFieldsUsingGETOK{}
}

// WithPayload adds the payload to the find entity fields using g e t o k response
func (o *FindEntityFieldsUsingGETOK) WithPayload(payload []*models.Field) *FindEntityFieldsUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find entity fields using g e t o k response
func (o *FindEntityFieldsUsingGETOK) SetPayload(payload []*models.Field) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindEntityFieldsUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Field, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// FindEntityFieldsUsingGETUnauthorizedCode is the HTTP code returned for type FindEntityFieldsUsingGETUnauthorized
const FindEntityFieldsUsingGETUnauthorizedCode int = 401

/*FindEntityFieldsUsingGETUnauthorized Unauthorized

swagger:response findEntityFieldsUsingGETUnauthorized
*/
type FindEntityFieldsUsingGETUnauthorized struct {
}

// NewFindEntityFieldsUsingGETUnauthorized creates FindEntityFieldsUsingGETUnauthorized with default headers values
func NewFindEntityFieldsUsingGETUnauthorized() *FindEntityFieldsUsingGETUnauthorized {
	return &FindEntityFieldsUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindEntityFieldsUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindEntityFieldsUsingGETForbiddenCode is the HTTP code returned for type FindEntityFieldsUsingGETForbidden
const FindEntityFieldsUsingGETForbiddenCode int = 403

/*FindEntityFieldsUsingGETForbidden Forbidden

swagger:response findEntityFieldsUsingGETForbidden
*/
type FindEntityFieldsUsingGETForbidden struct {
}

// NewFindEntityFieldsUsingGETForbidden creates FindEntityFieldsUsingGETForbidden with default headers values
func NewFindEntityFieldsUsingGETForbidden() *FindEntityFieldsUsingGETForbidden {
	return &FindEntityFieldsUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindEntityFieldsUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindEntityFieldsUsingGETNotFoundCode is the HTTP code returned for type FindEntityFieldsUsingGETNotFound
const FindEntityFieldsUsingGETNotFoundCode int = 404

/*FindEntityFieldsUsingGETNotFound Not Found

swagger:response findEntityFieldsUsingGETNotFound
*/
type FindEntityFieldsUsingGETNotFound struct {
}

// NewFindEntityFieldsUsingGETNotFound creates FindEntityFieldsUsingGETNotFound with default headers values
func NewFindEntityFieldsUsingGETNotFound() *FindEntityFieldsUsingGETNotFound {
	return &FindEntityFieldsUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindEntityFieldsUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
