// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// FindOneUsingGET1OKCode is the HTTP code returned for type FindOneUsingGET1OK
const FindOneUsingGET1OKCode int = 200

/*FindOneUsingGET1OK OK

swagger:response findOneUsingGET1OK
*/
type FindOneUsingGET1OK struct {

	/*
	  In: Body
	*/
	Payload *models.Entity `json:"body,omitempty"`
}

// NewFindOneUsingGET1OK creates FindOneUsingGET1OK with default headers values
func NewFindOneUsingGET1OK() *FindOneUsingGET1OK {
	return &FindOneUsingGET1OK{}
}

// WithPayload adds the payload to the find one using g e t1 o k response
func (o *FindOneUsingGET1OK) WithPayload(payload *models.Entity) *FindOneUsingGET1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find one using g e t1 o k response
func (o *FindOneUsingGET1OK) SetPayload(payload *models.Entity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindOneUsingGET1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindOneUsingGET1UnauthorizedCode is the HTTP code returned for type FindOneUsingGET1Unauthorized
const FindOneUsingGET1UnauthorizedCode int = 401

/*FindOneUsingGET1Unauthorized Unauthorized

swagger:response findOneUsingGET1Unauthorized
*/
type FindOneUsingGET1Unauthorized struct {
}

// NewFindOneUsingGET1Unauthorized creates FindOneUsingGET1Unauthorized with default headers values
func NewFindOneUsingGET1Unauthorized() *FindOneUsingGET1Unauthorized {
	return &FindOneUsingGET1Unauthorized{}
}

// WriteResponse to the client
func (o *FindOneUsingGET1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindOneUsingGET1ForbiddenCode is the HTTP code returned for type FindOneUsingGET1Forbidden
const FindOneUsingGET1ForbiddenCode int = 403

/*FindOneUsingGET1Forbidden Forbidden

swagger:response findOneUsingGET1Forbidden
*/
type FindOneUsingGET1Forbidden struct {
}

// NewFindOneUsingGET1Forbidden creates FindOneUsingGET1Forbidden with default headers values
func NewFindOneUsingGET1Forbidden() *FindOneUsingGET1Forbidden {
	return &FindOneUsingGET1Forbidden{}
}

// WriteResponse to the client
func (o *FindOneUsingGET1Forbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindOneUsingGET1NotFoundCode is the HTTP code returned for type FindOneUsingGET1NotFound
const FindOneUsingGET1NotFoundCode int = 404

/*FindOneUsingGET1NotFound Not Found

swagger:response findOneUsingGET1NotFound
*/
type FindOneUsingGET1NotFound struct {
}

// NewFindOneUsingGET1NotFound creates FindOneUsingGET1NotFound with default headers values
func NewFindOneUsingGET1NotFound() *FindOneUsingGET1NotFound {
	return &FindOneUsingGET1NotFound{}
}

// WriteResponse to the client
func (o *FindOneUsingGET1NotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
