// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindEntityFieldsUsingGETHandlerFunc turns a function with the right signature into a find entity fields using g e t handler
type FindEntityFieldsUsingGETHandlerFunc func(FindEntityFieldsUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindEntityFieldsUsingGETHandlerFunc) Handle(params FindEntityFieldsUsingGETParams) middleware.Responder {
	return fn(params)
}

// FindEntityFieldsUsingGETHandler interface for that can handle valid find entity fields using g e t params
type FindEntityFieldsUsingGETHandler interface {
	Handle(FindEntityFieldsUsingGETParams) middleware.Responder
}

// NewFindEntityFieldsUsingGET creates a new http.Handler for the find entity fields using g e t operation
func NewFindEntityFieldsUsingGET(ctx *middleware.Context, handler FindEntityFieldsUsingGETHandler) *FindEntityFieldsUsingGET {
	return &FindEntityFieldsUsingGET{Context: ctx, Handler: handler}
}

/*FindEntityFieldsUsingGET swagger:route GET /schemas/fields schema-controller findEntityFieldsUsingGET

findEntityFields

*/
type FindEntityFieldsUsingGET struct {
	Context *middleware.Context
	Handler FindEntityFieldsUsingGETHandler
}

func (o *FindEntityFieldsUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindEntityFieldsUsingGETParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
