// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFindOneUsingGET1Params creates a new FindOneUsingGET1Params object
// with the default values initialized.
func NewFindOneUsingGET1Params() FindOneUsingGET1Params {
	var ()
	return FindOneUsingGET1Params{}
}

// FindOneUsingGET1Params contains all the bound params for the find one using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters findOneUsingGET_1
type FindOneUsingGET1Params struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*eid
	  Required: true
	  In: path
	*/
	Eid string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *FindOneUsingGET1Params) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rEid, rhkEid, _ := route.Params.GetOK("eid")
	if err := o.bindEid(rEid, rhkEid, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *FindOneUsingGET1Params) bindEid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Eid = raw

	return nil
}
