// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSchemasUsingGETHandlerFunc turns a function with the right signature into a get schemas using g e t handler
type GetSchemasUsingGETHandlerFunc func(GetSchemasUsingGETParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSchemasUsingGETHandlerFunc) Handle(params GetSchemasUsingGETParams) middleware.Responder {
	return fn(params)
}

// GetSchemasUsingGETHandler interface for that can handle valid get schemas using g e t params
type GetSchemasUsingGETHandler interface {
	Handle(GetSchemasUsingGETParams) middleware.Responder
}

// NewGetSchemasUsingGET creates a new http.Handler for the get schemas using g e t operation
func NewGetSchemasUsingGET(ctx *middleware.Context, handler GetSchemasUsingGETHandler) *GetSchemasUsingGET {
	return &GetSchemasUsingGET{Context: ctx, Handler: handler}
}

/*GetSchemasUsingGET swagger:route GET /schemas/_entitys schema-controller getSchemasUsingGET

getSchemas

*/
type GetSchemasUsingGET struct {
	Context *middleware.Context
	Handler GetSchemasUsingGETHandler
}

func (o *GetSchemasUsingGET) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSchemasUsingGETParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
