// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// GetSchemasUsingGETOKCode is the HTTP code returned for type GetSchemasUsingGETOK
const GetSchemasUsingGETOKCode int = 200

/*GetSchemasUsingGETOK OK

swagger:response getSchemasUsingGETOK
*/
type GetSchemasUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Entity `json:"body,omitempty"`
}

// NewGetSchemasUsingGETOK creates GetSchemasUsingGETOK with default headers values
func NewGetSchemasUsingGETOK() *GetSchemasUsingGETOK {
	return &GetSchemasUsingGETOK{}
}

// WithPayload adds the payload to the get schemas using g e t o k response
func (o *GetSchemasUsingGETOK) WithPayload(payload []*models.Entity) *GetSchemasUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schemas using g e t o k response
func (o *GetSchemasUsingGETOK) SetPayload(payload []*models.Entity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchemasUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Entity, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSchemasUsingGETUnauthorizedCode is the HTTP code returned for type GetSchemasUsingGETUnauthorized
const GetSchemasUsingGETUnauthorizedCode int = 401

/*GetSchemasUsingGETUnauthorized Unauthorized

swagger:response getSchemasUsingGETUnauthorized
*/
type GetSchemasUsingGETUnauthorized struct {
}

// NewGetSchemasUsingGETUnauthorized creates GetSchemasUsingGETUnauthorized with default headers values
func NewGetSchemasUsingGETUnauthorized() *GetSchemasUsingGETUnauthorized {
	return &GetSchemasUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *GetSchemasUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetSchemasUsingGETForbiddenCode is the HTTP code returned for type GetSchemasUsingGETForbidden
const GetSchemasUsingGETForbiddenCode int = 403

/*GetSchemasUsingGETForbidden Forbidden

swagger:response getSchemasUsingGETForbidden
*/
type GetSchemasUsingGETForbidden struct {
}

// NewGetSchemasUsingGETForbidden creates GetSchemasUsingGETForbidden with default headers values
func NewGetSchemasUsingGETForbidden() *GetSchemasUsingGETForbidden {
	return &GetSchemasUsingGETForbidden{}
}

// WriteResponse to the client
func (o *GetSchemasUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetSchemasUsingGETNotFoundCode is the HTTP code returned for type GetSchemasUsingGETNotFound
const GetSchemasUsingGETNotFoundCode int = 404

/*GetSchemasUsingGETNotFound Not Found

swagger:response getSchemasUsingGETNotFound
*/
type GetSchemasUsingGETNotFound struct {
}

// NewGetSchemasUsingGETNotFound creates GetSchemasUsingGETNotFound with default headers values
func NewGetSchemasUsingGETNotFound() *GetSchemasUsingGETNotFound {
	return &GetSchemasUsingGETNotFound{}
}

// WriteResponse to the client
func (o *GetSchemasUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
