// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// ResetCurrentDsUsingPUTOKCode is the HTTP code returned for type ResetCurrentDsUsingPUTOK
const ResetCurrentDsUsingPUTOKCode int = 200

/*ResetCurrentDsUsingPUTOK OK

swagger:response resetCurrentDsUsingPUTOK
*/
type ResetCurrentDsUsingPUTOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseEntity `json:"body,omitempty"`
}

// NewResetCurrentDsUsingPUTOK creates ResetCurrentDsUsingPUTOK with default headers values
func NewResetCurrentDsUsingPUTOK() *ResetCurrentDsUsingPUTOK {
	return &ResetCurrentDsUsingPUTOK{}
}

// WithPayload adds the payload to the reset current ds using p u t o k response
func (o *ResetCurrentDsUsingPUTOK) WithPayload(payload *models.ResponseEntity) *ResetCurrentDsUsingPUTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reset current ds using p u t o k response
func (o *ResetCurrentDsUsingPUTOK) SetPayload(payload *models.ResponseEntity) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResetCurrentDsUsingPUTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ResetCurrentDsUsingPUTCreatedCode is the HTTP code returned for type ResetCurrentDsUsingPUTCreated
const ResetCurrentDsUsingPUTCreatedCode int = 201

/*ResetCurrentDsUsingPUTCreated Created

swagger:response resetCurrentDsUsingPUTCreated
*/
type ResetCurrentDsUsingPUTCreated struct {
}

// NewResetCurrentDsUsingPUTCreated creates ResetCurrentDsUsingPUTCreated with default headers values
func NewResetCurrentDsUsingPUTCreated() *ResetCurrentDsUsingPUTCreated {
	return &ResetCurrentDsUsingPUTCreated{}
}

// WriteResponse to the client
func (o *ResetCurrentDsUsingPUTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// ResetCurrentDsUsingPUTUnauthorizedCode is the HTTP code returned for type ResetCurrentDsUsingPUTUnauthorized
const ResetCurrentDsUsingPUTUnauthorizedCode int = 401

/*ResetCurrentDsUsingPUTUnauthorized Unauthorized

swagger:response resetCurrentDsUsingPUTUnauthorized
*/
type ResetCurrentDsUsingPUTUnauthorized struct {
}

// NewResetCurrentDsUsingPUTUnauthorized creates ResetCurrentDsUsingPUTUnauthorized with default headers values
func NewResetCurrentDsUsingPUTUnauthorized() *ResetCurrentDsUsingPUTUnauthorized {
	return &ResetCurrentDsUsingPUTUnauthorized{}
}

// WriteResponse to the client
func (o *ResetCurrentDsUsingPUTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ResetCurrentDsUsingPUTForbiddenCode is the HTTP code returned for type ResetCurrentDsUsingPUTForbidden
const ResetCurrentDsUsingPUTForbiddenCode int = 403

/*ResetCurrentDsUsingPUTForbidden Forbidden

swagger:response resetCurrentDsUsingPUTForbidden
*/
type ResetCurrentDsUsingPUTForbidden struct {
}

// NewResetCurrentDsUsingPUTForbidden creates ResetCurrentDsUsingPUTForbidden with default headers values
func NewResetCurrentDsUsingPUTForbidden() *ResetCurrentDsUsingPUTForbidden {
	return &ResetCurrentDsUsingPUTForbidden{}
}

// WriteResponse to the client
func (o *ResetCurrentDsUsingPUTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// ResetCurrentDsUsingPUTNotFoundCode is the HTTP code returned for type ResetCurrentDsUsingPUTNotFound
const ResetCurrentDsUsingPUTNotFoundCode int = 404

/*ResetCurrentDsUsingPUTNotFound Not Found

swagger:response resetCurrentDsUsingPUTNotFound
*/
type ResetCurrentDsUsingPUTNotFound struct {
}

// NewResetCurrentDsUsingPUTNotFound creates ResetCurrentDsUsingPUTNotFound with default headers values
func NewResetCurrentDsUsingPUTNotFound() *ResetCurrentDsUsingPUTNotFound {
	return &ResetCurrentDsUsingPUTNotFound{}
}

// WriteResponse to the client
func (o *ResetCurrentDsUsingPUTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
