// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewResetCurrentDsUsingPUTParams creates a new ResetCurrentDsUsingPUTParams object
// with the default values initialized.
func NewResetCurrentDsUsingPUTParams() ResetCurrentDsUsingPUTParams {
	var ()
	return ResetCurrentDsUsingPUTParams{}
}

// ResetCurrentDsUsingPUTParams contains all the bound params for the reset current ds using p u t operation
// typically these are obtained from a http.Request
//
// swagger:parameters resetCurrentDsUsingPUT
type ResetCurrentDsUsingPUTParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*dataSourceId
	  Required: true
	  In: path
	*/
	DataSourceID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ResetCurrentDsUsingPUTParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rDataSourceID, rhkDataSourceID, _ := route.Params.GetOK("dataSourceId")
	if err := o.bindDataSourceID(rDataSourceID, rhkDataSourceID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ResetCurrentDsUsingPUTParams) bindDataSourceID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.DataSourceID = raw

	return nil
}
