// Code generated by go-swagger; DO NOT EDIT.

package schema_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SyncSchemasUsingPUTHandlerFunc turns a function with the right signature into a sync schemas using p u t handler
type SyncSchemasUsingPUTHandlerFunc func(SyncSchemasUsingPUTParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SyncSchemasUsingPUTHandlerFunc) Handle(params SyncSchemasUsingPUTParams) middleware.Responder {
	return fn(params)
}

// SyncSchemasUsingPUTHandler interface for that can handle valid sync schemas using p u t params
type SyncSchemasUsingPUTHandler interface {
	Handle(SyncSchemasUsingPUTParams) middleware.Responder
}

// NewSyncSchemasUsingPUT creates a new http.Handler for the sync schemas using p u t operation
func NewSyncSchemasUsingPUT(ctx *middleware.Context, handler SyncSchemasUsingPUTHandler) *SyncSchemasUsingPUT {
	return &SyncSchemasUsingPUT{Context: ctx, Handler: handler}
}

/*SyncSchemasUsingPUT swagger:route PUT /schemas/sync/{dataSourceId} schema-controller syncSchemasUsingPUT

syncSchemas

*/
type SyncSchemasUsingPUT struct {
	Context *middleware.Context
	Handler SyncSchemasUsingPUTHandler
}

func (o *SyncSchemasUsingPUT) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSyncSchemasUsingPUTParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
