// Code generated by go-swagger; DO NOT EDIT.

package permission_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// AddPermissionUsingPOSTOKCode is the HTTP code returned for type AddPermissionUsingPOSTOK
const AddPermissionUsingPOSTOKCode int = 200

/*AddPermissionUsingPOSTOK OK

swagger:response addPermissionUsingPOSTOK
*/
type AddPermissionUsingPOSTOK struct {

	/*
	  In: Body
	*/
	Payload *models.Permission `json:"body,omitempty"`
}

// NewAddPermissionUsingPOSTOK creates AddPermissionUsingPOSTOK with default headers values
func NewAddPermissionUsingPOSTOK() *AddPermissionUsingPOSTOK {
	return &AddPermissionUsingPOSTOK{}
}

// WithPayload adds the payload to the add permission using p o s t o k response
func (o *AddPermissionUsingPOSTOK) WithPayload(payload *models.Permission) *AddPermissionUsingPOSTOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add permission using p o s t o k response
func (o *AddPermissionUsingPOSTOK) SetPayload(payload *models.Permission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddPermissionUsingPOSTOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddPermissionUsingPOSTCreatedCode is the HTTP code returned for type AddPermissionUsingPOSTCreated
const AddPermissionUsingPOSTCreatedCode int = 201

/*AddPermissionUsingPOSTCreated Created

swagger:response addPermissionUsingPOSTCreated
*/
type AddPermissionUsingPOSTCreated struct {
}

// NewAddPermissionUsingPOSTCreated creates AddPermissionUsingPOSTCreated with default headers values
func NewAddPermissionUsingPOSTCreated() *AddPermissionUsingPOSTCreated {
	return &AddPermissionUsingPOSTCreated{}
}

// WriteResponse to the client
func (o *AddPermissionUsingPOSTCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddPermissionUsingPOSTUnauthorizedCode is the HTTP code returned for type AddPermissionUsingPOSTUnauthorized
const AddPermissionUsingPOSTUnauthorizedCode int = 401

/*AddPermissionUsingPOSTUnauthorized Unauthorized

swagger:response addPermissionUsingPOSTUnauthorized
*/
type AddPermissionUsingPOSTUnauthorized struct {
}

// NewAddPermissionUsingPOSTUnauthorized creates AddPermissionUsingPOSTUnauthorized with default headers values
func NewAddPermissionUsingPOSTUnauthorized() *AddPermissionUsingPOSTUnauthorized {
	return &AddPermissionUsingPOSTUnauthorized{}
}

// WriteResponse to the client
func (o *AddPermissionUsingPOSTUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddPermissionUsingPOSTForbiddenCode is the HTTP code returned for type AddPermissionUsingPOSTForbidden
const AddPermissionUsingPOSTForbiddenCode int = 403

/*AddPermissionUsingPOSTForbidden Forbidden

swagger:response addPermissionUsingPOSTForbidden
*/
type AddPermissionUsingPOSTForbidden struct {
}

// NewAddPermissionUsingPOSTForbidden creates AddPermissionUsingPOSTForbidden with default headers values
func NewAddPermissionUsingPOSTForbidden() *AddPermissionUsingPOSTForbidden {
	return &AddPermissionUsingPOSTForbidden{}
}

// WriteResponse to the client
func (o *AddPermissionUsingPOSTForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// AddPermissionUsingPOSTNotFoundCode is the HTTP code returned for type AddPermissionUsingPOSTNotFound
const AddPermissionUsingPOSTNotFoundCode int = 404

/*AddPermissionUsingPOSTNotFound Not Found

swagger:response addPermissionUsingPOSTNotFound
*/
type AddPermissionUsingPOSTNotFound struct {
}

// NewAddPermissionUsingPOSTNotFound creates AddPermissionUsingPOSTNotFound with default headers values
func NewAddPermissionUsingPOSTNotFound() *AddPermissionUsingPOSTNotFound {
	return &AddPermissionUsingPOSTNotFound{}
}

// WriteResponse to the client
func (o *AddPermissionUsingPOSTNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
