// Code generated by go-swagger; DO NOT EDIT.

package permission_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/roscopecoltran/admin-on-rest-server/server/models"
)

// FindUserUsingGETOKCode is the HTTP code returned for type FindUserUsingGETOK
const FindUserUsingGETOKCode int = 200

/*FindUserUsingGETOK OK

swagger:response findUserUsingGETOK
*/
type FindUserUsingGETOK struct {

	/*
	  In: Body
	*/
	Payload *models.Permission `json:"body,omitempty"`
}

// NewFindUserUsingGETOK creates FindUserUsingGETOK with default headers values
func NewFindUserUsingGETOK() *FindUserUsingGETOK {
	return &FindUserUsingGETOK{}
}

// WithPayload adds the payload to the find user using g e t o k response
func (o *FindUserUsingGETOK) WithPayload(payload *models.Permission) *FindUserUsingGETOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find user using g e t o k response
func (o *FindUserUsingGETOK) SetPayload(payload *models.Permission) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindUserUsingGETOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FindUserUsingGETUnauthorizedCode is the HTTP code returned for type FindUserUsingGETUnauthorized
const FindUserUsingGETUnauthorizedCode int = 401

/*FindUserUsingGETUnauthorized Unauthorized

swagger:response findUserUsingGETUnauthorized
*/
type FindUserUsingGETUnauthorized struct {
}

// NewFindUserUsingGETUnauthorized creates FindUserUsingGETUnauthorized with default headers values
func NewFindUserUsingGETUnauthorized() *FindUserUsingGETUnauthorized {
	return &FindUserUsingGETUnauthorized{}
}

// WriteResponse to the client
func (o *FindUserUsingGETUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// FindUserUsingGETForbiddenCode is the HTTP code returned for type FindUserUsingGETForbidden
const FindUserUsingGETForbiddenCode int = 403

/*FindUserUsingGETForbidden Forbidden

swagger:response findUserUsingGETForbidden
*/
type FindUserUsingGETForbidden struct {
}

// NewFindUserUsingGETForbidden creates FindUserUsingGETForbidden with default headers values
func NewFindUserUsingGETForbidden() *FindUserUsingGETForbidden {
	return &FindUserUsingGETForbidden{}
}

// WriteResponse to the client
func (o *FindUserUsingGETForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// FindUserUsingGETNotFoundCode is the HTTP code returned for type FindUserUsingGETNotFound
const FindUserUsingGETNotFoundCode int = 404

/*FindUserUsingGETNotFound Not Found

swagger:response findUserUsingGETNotFound
*/
type FindUserUsingGETNotFound struct {
}

// NewFindUserUsingGETNotFound creates FindUserUsingGETNotFound with default headers values
func NewFindUserUsingGETNotFound() *FindUserUsingGETNotFound {
	return &FindUserUsingGETNotFound{}
}

// WriteResponse to the client
func (o *FindUserUsingGETNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
