package permission_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/validate"

	"github.com/roscopecoltran/admin-on-rest-server/server/api"

	strfmt "github.com/go-openapi/strfmt"
)

// BusinessLogicListUsingGET1 executes the core logic of the related
// route endpoint.
func BusinessLogicListUsingGET1(f func(ctx *gin.Context, params *ListUsingGET1Params) *api.Response) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		// generate params from request
		params := &ListUsingGET1Params{}
		err := params.bindRequest(ctx)
		if err != nil {
			errObj := err.(*errors.CompositeError)
			problem := api.Problem{
				Title:  "Unprocessable Entity.",
				Status: int(errObj.Code()),
				Detail: errObj.Error(),
			}
			ctx.Writer.Header().Set("Content-Type", "application/problem+json")
			ctx.JSON(problem.Status, problem)
			return
		}

		resp := f(ctx, params)
		switch resp.Code {
		case http.StatusNoContent:
			ctx.AbortWithStatus(resp.Code)
		default:
			ctx.JSON(resp.Code, resp.Body)
		}
	}
}

// ListUsingGET1Params contains all the bound params for the list using g e t 1 operation
// typically these are obtained from a http.Request
//
// swagger:parameters listUsingGET_1
type ListUsingGET1Params struct {

	/*roleId
	  Required: true
	  In: query
	*/
	RoleID string
}

// ListUsingGET1ParamsFromCtx gets the params struct from the gin context.
func ListUsingGET1ParamsFromCtx(ctx *gin.Context) *ListUsingGET1Params {
	params, _ := ctx.Get("params")
	return params.(*ListUsingGET1Params)
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *ListUsingGET1Params) bindRequest(ctx *gin.Context) error {
	var res []error
	formats := strfmt.NewFormats()

	qs := runtime.Values(ctx.Request.URL.Query())

	qRoleID, qhkRoleID, _ := qs.GetOK("roleId")
	if err := o.bindRoleID(qRoleID, qhkRoleID, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListUsingGET1Params) bindRoleID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("roleId", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("roleId", "query", raw); err != nil {
		return err
	}

	o.RoleID = raw

	return nil
}

// vim: ft=go
